version: '3.7'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./volumes/mysql
    restart: always
    env_file:
      - .env
  app:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./volumes/wordpress
    ports:
      - "8080:80"
    restart: always
    env_file:
      - .env
